# Generated by Django 3.0.8 on 2020-07-20 06:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('conductor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion_recojo', models.CharField(max_length=100)),
                ('direccion_detino', models.CharField(max_length=100)),
                ('fecha_hora_solicitado', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_atendido', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_terminado', models.DateTimeField(blank=True, null=True)),
                ('puntos_valoracion', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('estado', models.IntegerField(choices=[(0, 'Cancelado'), (1, 'Pendiente'), (2, 'Atendido'), (3, 'Terminado')], default=1)),
                ('distrito_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='taxis.Distrito')),
                ('distrito_recojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recojo', to='taxis.Distrito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxis.Vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxis.Distrito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
